# This rule is not used by the project sartorproj itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over autoscaling.sartorproj.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: sartorproj
    app.kubernetes.io/managed-by: kustomize
  name: tailoring-admin-role
rules:
- apiGroups:
  - autoscaling.sartorproj.io
  resources:
  - tailorings
  verbs:
  - '*'
- apiGroups:
  - autoscaling.sartorproj.io
  resources:
  - tailorings/status
  verbs:
  - get
